#!/bin/bash
ip="192.168.2.10"
mongo <<-EOF
     cfg={ _id:"rs", members:[ {_id:0,host:'${ip}:27017',priority:100}, {_id:1,host:'${ip}:27020',priority:90}, {_id:3,host:'${ip}:27021',arbiterOnly:true}] }
     rs.initiate(cfg)
     use admin
     db.createUser({user:'root',pwd:'123456',customData:{description:"root"},roles:[{'role':'root','db':'admin'}]})
     exit
EOF
