#!/bin/bash

sudo apt-get install -y docker.io
sudo service docker start
sudo pip install -U docker-compose
sudo docker pull mongo:3.6.9
sudo docker pull ubuntu:16.04
sudo docker build -t ubuntu-flask .

