version: "3"

services:
  DB_inter:
    image: ubuntu-flask2:latest
    network_mode: host
    volumes:  
      - ./:/home
    ports:
      - "5000:5000"
    command: 
      - /bin/sh
      - -c
      - |
         cd /home
         gunicorn interface:app -c gunicorn.conf.py
#python3 code/app.py
