version: "3"

services:
  db:
    image: mongo:3.6.9

    volumes:
     - ./data:/data/db
    ports: 
     - "27017:27017"
    command: 
      - /bin/sh
      - -c
      - |
         mongod --replSet rs
         mongo
         cfg={ _id:"rs", members:[ {_id:0,host:'192.168.2.133:27017',priority:100}, {_id:1,host:'192.168.2.133:27018',priority:90}, {_id:2,host:'192.168.2.133:27019',arbiterOnly:true}] }
         rs.initiate(cfg)
         
  db2:
    image: mongo:3.6.9

    volumes:
     - ./data2:/data/db
    ports: 
     - "27018:27017"
    command: mongod --replSet rs
  db3:
    image: mongo:3.6.9

    volumes:
     - ./data3:/data/db
    ports: 
     - "27019:27017"
    command: mongod --replSet rs
  DB_inter:
    image: ubuntu-flask2:latest
    network_mode: host
    ports:
      - "5000:5000"
    volumes:  
      - ./:/home
    ports:
      - "5000:5000"
    command: 
      - /bin/sh
      - -c
      - |
         cd /home
         python3 ./app2.py
#python3 code/app.py
#gunicorn interface:app -c gunicorn.conf.py
